; PlatformIO Project Configuration File
;
; Supported platforms for the MobiFlight firmware are:
; atmega2560
; promicro
; uno
;
; Version numbers for releases are automatically applied by GitHub
; during the release build process based on the tag associated with
; the GitHub release.

; To ensure builds work correctly in GitHub the default_envs
; should always be set to all supported MobiFlight platforms.
; If you want to only build a single platform locally during
; development use VSCode to change the target to a non-default
; by clicking on the target name in the bottom status bar.
[platformio]

	default_envs 			= esp32-s3-devkitm-1
	data_dir        		= ./src/T20_MFCC_212/219/data
	build_cache_dir         = ./.pio/build_cache

[env:esp32-s3-devkitm-1]
	platform 				= espressif32
	board 					= esp32-s3-devkitm-1
	framework 				= arduino
	monitor_speed 			= 115200
	board_build.filesystem  = littlefs
	board_build.partitions 	= min_spiffs.csv

	lib_ldf_mode 			= deep+
	lib_archive 			= no

    # [v214] gnu++17 표준 강제 적용 (Warning 해결 핵심)
	build_unflags =
					-std=gnu++11
					-std=c++11

	build_flags =
				    -std=gnu++17
				    # 라이브러리 내부 예제 파일들이 빌드에 포함되지 않도록 정의
				    -D CONFIG_DSP_OPTIMIZED=1
					-D CONFIG_DSP_OPTIMIZATION_AES3=y
				    -D CONFIG_IDF_TARGET_ESP32S3=1
				    -D SOC_SDMMC_HOST_SUPPORTED

				    ; esp-dsp 헤더 경로 강제 포함
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/common/include
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/fft/include
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/filter/include
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/dotprod/include
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/dotprod/float
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/dotprod/fixed
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/math/include
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/matrix/include
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/iir/include
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/fir/include
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/conv/include
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/conv/float
				    -I .pio/libdeps/esp32-s3-devkitm-1/esp-dsp/modules/support/include

	; 내가 작성한 src/ 폴더의 코드에만 적용되는 엄격한 경고 플래그
	;src_build_flags =
	;    -Wall
	;    -Wextra
	;    -Wunused-variable
	;    -Wunused-const-variable


	build_src_filter =
						-<*>                          ; 일단 모든 파일을 제외
						+<main.cpp>                    ; 루트의 main.cpp만 포함
						+<T20_MFCC_212/219/>
						;+<T20_MFCC_212/214/>
						; +<T20_MFCC_011/212/>           ; 212 폴더 내의 소스들만 포함

						;   +<*>                           ; src 폴더 바로 아래의 파일들(main.cpp 등) 포함
						;   -<.git/> -<.svn/>              ; 기본 제외 설정
						;   -<010/> -<T004/>               ; 원치 않는 하위 폴더 명시적 제외
						;   -<T20_MFCC_011/030/>           ; T20... 하위 폴더 중 제외할 것
						;   -<T20_MFCC_011/211/>           ; T20... 하위 폴더 중 제외할 것
						;   +<T20_MFCC_011/212/>           ; 목표로 하는 212 폴더 포함


	lib_extra_dirs =

	lib_deps =
	    FS
	    SD_MMC
	    SPI
		bblanchon/ArduinoJson @ ^7.4.3
		esp32async/ESPAsyncWebServer @ ^3.10.1

		sparkfun/SparkFun BMI270 Arduino Library @ ^1.0.3
		martinbudden/VectorQuaternionMatrix @ ^0.4.10
		martinbudden/SensorFusion @ ^0.2.14
		
		knolleary/PubSubClient@^2.8

		https://github.com/espressif/esp-dsp.git#v1.7.1
		; espressif/esp-dsp @ ^1.7.1

		; greiman/SdFat@^2.3.1
	extra_scripts =
		pre:shared/get_version.py
		pre:shared/setup_esp_dsp.py

; [env-esp32doit]
; platform = espressif32
; board = esp32doit-devkit-v1
; framework = arduino
; monitor_speed = 115200
; board_build.partitions 	= huge_app.csv
; lib_extra_dirs =

; lib_deps =
; 	sparkfun/SparkFun BMI270 Arduino Library @ ^1.0.3
; 	martinbudden/VectorQuaternionMatrix @ ^0.4.10
; 	martinbudden/SensorFusion @ ^0.2.14

; extra_scripts =
; 	pre:shared/get_version.py